FROM osrf/ros:kinetic-desktop-full-xenial
ARG pkgs
RUN apt-get update \
    && apt-get install -y ros-kinetic-desktop-full apt-rdepends \
    && rm -rf /var/lib/apt/lists/*
ENV pkgs=$pkgs
ENTRYPOINT /usr/bin/apt-rdepends -r ${pkgs} | grep 'Reverse Depends:' | awk '{print $3}' | tr '\r\n' ',' | sed 's:,:, :g'
