FROM osrf/ros:foxy-desktop-focal
ARG pkgs
RUN apt-get update \
    && apt-get install -y ros-foxy-desktop apt-rdepends \
    && rm -rf /var/lib/apt/lists/*
ENV pkgs=$pkgs
ENTRYPOINT /usr/bin/apt-rdepends -r ${pkgs} | grep 'Reverse Depends:' | awk '{print $3}' | sort | uniq | tr '\r\n' ',' | sed 's:,:, :g'
