FROM osrf/ros:noetic-desktop-full-focal
ARG pkgs
RUN apt-get update \
    && apt-get install -y ros-noetic-desktop-full apt-rdepends \
    && rm -rf /var/lib/apt/lists/*
ENV pkgs=$pkgs
ENTRYPOINT /usr/bin/apt-rdepends -r ${pkgs} | grep -v 'Reverse Depends:' | tr '\r\n' ', '
